# Site settings
title: Flexberry PLATFORM Documentation
email: mail@flexberry.net
description: > # this means to ignore newlines until "baseurl:"
  Technical documentation for Flexberry PLATFORM Projects. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flexberry.github.io" # the base hostname & protocol for your site
repository: "Flexberry/flexberry.github.io"
twitter_username: flexberry
github_username:  Flexberry

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Flexberry PLATFORM
# this appears on the top navigation bar next to the home button

site_title: Flexberry PLATFORM Documentation
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Flexberry
# this appears in the footer

github_editme_path: Flexberry/flexberry.github.io/edit/master/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

disqus: true

disqus_shortname: flexberry-doc
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .vscode/
  - .gitignore
  - .gitmodules
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
# these are the files and directories that jekyll will exclude from the build

feedback_subject_line: Flexberry documentation

feedback_email: mail@flexberry.net
# used as a contact email for the Feedback link in the top navigation bar

# Build settings
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

redcarpet:
  extensions: ['tables']

collections:
  tooltips:
    output: false
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: home_sidebar

# these are defaults used for the frontmatter for these file types

highlighter: rouge
# library used for syntax highlighting


sidebars:
- home_sidebar
- mydoc_sidebar
- product1_sidebar
- product2_sidebar
- ember-flexberry_sidebar
- ember-flexberry-data_sidebar
- ember-flexberry-security_sidebar
- ember-flexberry-gis_sidebar
- flexberry-aspnet_sidebar
- flexberry-designer_sidebar
- flexberry-odataservice_sidebar
- flexberry-orm_sidebar
- flexberry-platform_sidebar
- guide-base-tech_sidebar
- guide-tasks_sidebar
- guide-practical-guides_sidebar
- other
